### ISSUE TITLE
Project table prefix not taken into account

### ISSUE THREAD

**Issue by julien101** [Nemmo/yii2-attachments#20]
Following the basic installation process, my attachments table does not contain the project prefix specified in my main.php:
'tablePrefix' => 'abc_',
The fix is probably simple:
1) Modify File.php:
    public static function tableName()
    {
        return '{{%attach_file}}';
    }
2) Fix m150127_040544_add_attachments up() and down() to support tablePrefix

**Comment by Nemmo** [comment]
On my project according to the my architecture it must be without table prefix. If you need the table prefix you can fork and do that by yourself
