### ISSUE TITLE
Can't save single upload image

### ISSUE THREAD

**Issue by ramil8090** [Nemmo/yii2-attachments#22]
In FileController.php -> actionUpload we can't save single uploaded image. Where ELSE block you must store file name in $result array. Code must like this

if (is_array($model->file)) {
           foreach ($model->file as $file) {
                $path = $this->getModule()->getUserDirPath() . DIRECTORY_SEPARATOR . $file->name;
                $file->saveAs($path);
                $result['uploadedFiles'][] = $file->name;
            }
           } else {
                $path = $this->getModule()->getUserDirPath() . DIRECTORY_SEPARATOR . $model->file->name;
                $model->file->saveAs($path);                
                !!!!add this string!!!!  --> $result['uploadedFiles'][] = $model->file->name;
            }

**Comment by Nemmo** [comment]
Why you cannot save single uploaded image? What is wrong? On my site it works fine!

**Comment by ramil8090** [comment]
It don't save single file when he uploaded asynchronously because in returned JSON there is no filename, but only empty array

**Comment by Nemmo** [comment]
Single file? What configuration options did you use?

**Comment by ramil8090** [comment]
I will checkout configuration in monday.

**Comment by ramil8090** [comment]
Sorry, but i already delete code that emulate error. Anyway i will try again when i will be in office but later. Now i think we must close this issue
