### ISSUE TITLE
Stop form submit on error

### ISSUE THREAD

**Issue by jonazu** [Nemmo/yii2-attachments#24]
Thank you very much for this extension. After some hours I managed to get it to work.

When I submit the form and there is an error with the extension, the form just gets submitted anyway. I see in the documentation a deprecated onclick action so I assumed this should work somehow. Is there a setting I've missed?

**Comment by Nemmo** [comment]
Fixed on https://github.com/Nemmo/yii2-attachments/commit/f45842cdc6479affa0a06255b5a8f13b6e32d9f9, please test it
