### ISSUE TITLE
Как разрешить добавлять несколько mimeTipes? 

### ISSUE THREAD

**Issue by Kotesch** [Nemmo/yii2-attachments#28]
Писал так: 
'mimeTypes' => ['image/jpg' , 'image/png'],

'mimeTypes' => 'image/jpg , image/png',

пишет что разрешено, но не грузит

Подскажи как правильно

**Comment by Nemmo** [comment]
Только что проверил с ```'mimeTypes' => ['image/png', 'image/jpeg']```, все работает отлично. Как не грузит?

**Comment by Kotesch** [comment]
привет, решил проблему вот так:  
'mimeTypes' =>
                    'image/png, '
                    .'image/jpeg, '
                    .'image/x-icon, ',

**Comment by Nemmo** [comment]
Конкатенацией строк? А цельной строкой не работает?
