### ISSUE TITLE
Не сохраняет в базу данных

### ISSUE THREAD

**Issue by Kotesch** [Nemmo/yii2-attachments#33]
Привет ещё раз, живём в России, так что предлагаю общаться по русски. Перерыл всё расширение, всё вроде правильно сделал. всё работает, кроме сохранения изображений в базу данных. Использую yii2 basic

**Comment by Nemmo** [comment]
Я казах из Казахстана. 
Что значит сохранение изображений в БД? Через блобы что ли?

**Comment by Kotesch** [comment]
Извини, ну вообщем всё равно по Русски разговариваем.  Неправильно выразился,  названия изображений не сохраняет в бд.  И при этом сами изображения сохраняет только в папке Temp

**Comment by Nemmo** [comment]
Тестировал - все работает. Не могу понять что может быть

**Comment by mrsad** [comment]
@Kotesch модель-то сохраняешь? :)
