### ISSUE TITLE
Add some restrictions to files

### ISSUE THREAD

**Issue by maxxer** [Nemmo/yii2-attachments#4]
It would be great to be able to add some restrictions to the files the user can upload, on a per model basis:

- [x] Limit the max number of files 
- [x] Limit the mimetype/extension of files
- [ ] Limit the max number of files per mimetype (maybe this is excessive)

**Comment by Nemmo** [comment]
I will try to do that that weekends

**Comment by Nemmo** [comment]
Just now added rules, please test it

**Comment by maxxer** [comment]
ok thanks, I will test. one question: is the limit allowed per model or just in global config?

**Comment by Nemmo** [comment]
Now globally, I have not thought about how do that per model. If u know that please tell me (:
