### ISSUE TITLE
Error in execute migration

### ISSUE THREAD

**Issue by kriptograf** [Nemmo/yii2-attachments#52]
У вас возникает ошибка при выполнении миграции. 
`$ php yii migrate/up --migrationPath=@vendor/nemmo/yii2-attachments/src/migrations
Yii Migration Tool (based on Yii v2.0.11-dev)

Total 1 new migration to be applied:
	m150127_040544_add_attachments

Apply the above migration? (yes|no) [no]:y
*** applying m150127_040544_add_attachments
PHP Fatal error:  Class 'm150127_040544_add_attachments' not found in /home/debian/sites/avega2.loc/vendor/yiisoft/yii2/console/controllers/MigrateController.php on line 191
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'm150127_040544_add_attachments' not found'

in /home/debian/sites/avega2.loc/vendor/yiisoft/yii2/console/controllers/MigrateController.php:191

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}`

Предположительно,  в файле миграции не нужен namespace.
`namespace nemmo\attachments\migrations;` стр.3
 После его удаления миграция отработала без ошибок.

**Comment by Nemmo** [comment]
ДД!

Попробуйте так:
```php
    	'controllerMap' => [
		...
		'migrate' => [
			'class' => 'yii\console\controllers\MigrateController',
			'migrationNamespaces' => [
				'nemmo\attachments\migrations',
			],
		],
		...
    	],
```


```
php yii migrate/up
```

**Comment by kriptograf** [comment]
Спасибо. Как вариант можно использовать, если namespace в файле миграции крайне необходим. Тогда не мешало бы указать это в документации, что бы другие пользователи не попадали в такую же ситуацию.

**Comment by Nemmo** [comment]
Да, помню, но версию еще не выпускал. Просто у вас composer настроен на девелоперскую версию, которая не стабильна.
