### ISSUE TITLE
Migrations fail with message class not found

### ISSUE THREAD

**Issue by philippfrenzel** [Nemmo/yii2-attachments#54]
Hi, since your namespace cleanup, the migrations aren't working anymore. I'm not able to solve it, as you are using the getModule function within the migrate to retrieve the table name from the config - do you have an idea how to fix this?

Thanks Philipp

**Comment by philippfrenzel** [comment]
Hi, pls. see:

https://github.com/dmstr/yii2-migrate-command/issues/19

It looks like the class is not registered in the global namespace

**Comment by schmunk42** [comment]
It's more a Yii2 issue I think, see https://github.com/yiisoft/yii2/issues/384
There was a discussion about implementing this via Yii app params, but now it's done via namespaces.

**Comment by schmunk42** [comment]
You need to require Yii >= 2.0.10, when using namespaced migrations. See also https://github.com/yiisoft/yii2/issues/13356

**Comment by Nemmo** [comment]
Install [1.0.0-beta.2](https://github.com/Nemmo/yii2-attachments/releases/tag/1.0.0-beta.2) of that ext if you have not to upgrade yii -> 2.0.10

**Comment by schmunk42** [comment]
@philippfrenzel That's the way to go then, since this extension is in beta, these updates are fine.

I think this can be closed.
