### ISSUE TITLE
How can I use the file in a controller?

### ISSUE THREAD

**Issue by philippfrenzel** [Nemmo/yii2-attachments#6]
e.g. I wanna open a word file (attachement) and then wanna replace stuff inside to deploy to user?

Thanks Philipp

**Comment by Nemmo** [comment]
I have not understood what do u want to do. Could u explain/give me an example?

**Comment by philippfrenzel** [comment]
I wanna do this:

http://phpword.readthedocs.org/en/latest/templates-processing.html

Which means:

´´´
$templateProcessor = new TemplateProcessor('Template.docx');
$templateProcessor->setValue('Name', 'Somebody someone');
$templateProcessor->setValue('Street', 'Coming-Undone-Street 32');
´´´

Where Template.docx is the file I uploaded to a model, using your module;)

**Comment by Nemmo** [comment]
Now u can use 
```php
model->files[0]->path // for single file
```
or
```php
foreach ($model->files as $file) {
    echo $file->path;
}
```
Is that all you need to?

**Comment by philippfrenzel** [comment]
Jep! exactly! ;) THanks a Lot
